[envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
]
[envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=iterum --doctest-modules -vvvx {args}"
no-cov = "cov --no-cov {args}"

[[envs.test.matrix]]
python = ["311", "312"]

[envs.lint]
detached = true
dependencies = [
  "pre-commit>=3.3.0",
  "pyright>=1.1.0",
]

[envs.lint.scripts]
type = "pyright iterum type_tests"
fmt = [
  "pre-commit run --all-files",
]
all = [
  "fmt",
  "type",
]

[envs.docs]
dependencies = [
  "mkdocs~=1.4.3",
  "mkdocs-material~=9.1.17",
  # Plugins
  "mkdocs-minify-plugin~=0.5.0",
  "mkdocs-git-revision-date-localized-plugin~=1.1.0",
  "mkdocstrings-python~=1.1.2",
  "mkdocs-redirects~=1.1.0",
  "mkdocs-glightbox~=0.3.0",
  # https://github.com/jimporter/mike/issues/82#issuecomment-1172913929
  "mike @ https://github.com/jimporter/mike/archive/392d57b8bb9d14bcedf2451a0dc302709f8055eb.zip",
  # Extensions
  "mkdocs-click~=0.8.0",
  "pymdown-extensions~=10.0.1",
  # Necessary for syntax highlighting in code blocks
  "pygments~=2.15.1",
  # Validation
  # https://github.com/linkchecker/linkchecker/pull/669#issuecomment-1267236287
  "linkchecker @ git+https://github.com/linkchecker/linkchecker.git@d9265bb71c2054bf57b8c5734a4825d62505c779",
]

[envs.docs.scripts]
build = "mkdocs build --clean --strict {args}"
serve = "mkdocs serve {args}"
