site_name: iterum
site_author: tjsmart

repo_url: https://github.com/tjsmart/iterum
repo_name: tjsmart/iterum

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: red
    accent: red

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tjsmart

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/tjsmart"  target="_blank" rel="noopener">Tyler Smart</a>

nav:
  - Overview: 'index.md'
  - API: 'api.md'

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          options:
            # Headings
            show_root_heading: true
            show_root_full_path: true
            # Docstrings
            show_if_no_docstring: false
            # Signatures/annotations
            show_signature_annotations: true
            # Member options
            members_order: source
            # Other
            show_bases: true
            show_source: true
