name: Check Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run:
    name: Check Docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install hatch
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade hatch

    - name: Build docs
      run: hatch run docs:build
