name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --locked --group dev

    - name: Run linters
      run: |
        uv run ruff check .
        uv run ruff format --check .
        uv run pyright src/iterum type_tests
